[package] #是一个片段（section）标题，表明下面的语句用来配置一个包
name = "hello_cargo"    #项目的名称
version = "0.1.0"       #项目的版本
edition = "2021"        #RUST版本

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]  #罗列项目依赖的片段 备注：在RUST中，代码包被称为crates(箱子)
